# Vector Arithmetic

In [1]:
import numpy as np

# 
u = np.array([[2], [5]])
v = np.array([[4], [7]])

# 
u_minus_v = u - v  # u - v
u_plus_v = u + v  # u + v
three_u_minus_five_v = 3*u - 5*v  # 3u - 5v
two_u_plus_four_v = 2*u + 4*v  # 2u + 4v

# 
print("1. u - v =\n", u_minus_v, "\n")
print("2. u + v =\n", u_plus_v, "\n")
print("3. 3u - 5v =\n", three_u_minus_five_v, "\n")
print("4. 2u + 4v =\n", two_u_plus_four_v, "\n")


1. u - v =
 [[-2]
 [-2]] 

2. u + v =
 [[ 6]
 [12]] 

3. 3u - 5v =
 [[-14]
 [-20]] 

4. 2u + 4v =
 [[20]
 [38]] 



# Matrix Arithmetic

In [2]:
import numpy as np

# 
A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
B = np.array([[1, 1, 4], [3, 2, 5], [4, 0, 9]])

# 
A_plus_B = A + B  # A + B
A_minus_B = A - B  # A - B
two_A_minus_three_B = 2*A - 3*B  # 2A - 3B
five_A_plus_two_B = 5*A + 2*B  # 5A + 2B

# 
print("5. A + B =\n", A_plus_B, "\n")
print("6. A - B =\n", A_minus_B, "\n")
print("7. 2A - 3B =\n", two_A_minus_three_B, "\n")
print("8. 5A + 2B =\n", five_A_plus_two_B, "\n")


5. A + B =
 [[ 4  7  5]
 [ 5  8 14]
 [ 9  1 12]] 

6. A - B =
 [[ 2  5 -3]
 [-1  4  4]
 [ 1  1 -6]] 

7. 2A - 3B =
 [[  3   9 -10]
 [ -5   6   3]
 [ -2   2 -21]] 

8. 5A + 2B =
 [[17 32 13]
 [16 34 55]
 [33  5 33]] 



# Matrix/Vector Multiplication

In [3]:
import numpy as np


A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
u = np.array([[3], [1], [2]])
w = np.array([[0], [1], [0]])   


B = np.array([[1, 1, 4, 9], [3, 2, 5, 1], [2, 7, 0, 9]])
v = np.array([[2], [5], [0], [1]])

 
Au = np.dot(A, u)  # A * u
Bv = np.dot(B, v)  # B * v
Aw = np.dot(A, w)  # A * w

 
print("9. Au =\n", Au, "\n")
print("10. Bv =\n", Bv, "\n")
print("11. Aw =\n", Aw, "\n")


9. Au =
 [[17]
 [30]
 [22]] 

10. Bv =
 [[16]
 [17]
 [48]] 

11. Aw =
 [[6]
 [6]
 [1]] 



# Matrix Multiplication:

In [4]:
import numpy as np

 
A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
B = np.array([[1, 1, 4], [3, 2, 5], [4, 0, 9]])
C = np.array([[1, 4], [6, 2], [0, 1]])
D = np.array([[1, 2, 4, 2], [3, 2, 1, 0]])

 
AB = np.dot(A, B)  # A * B
BA = np.dot(B, A)  # B * A
CD = np.dot(C, D)  # C * D


print("12. AB =\n", AB, "\n")
print("13. BA =\n", BA, "\n")
print("14. CD =\n", CD, "\n")


12. AB =
 [[ 25  15  51]
 [ 56  14 119]
 [ 20   7  52]] 

13. BA =
 [[25 16 22]
 [38 35 36]
 [57 33 31]] 

14. CD =
 [[13 10  8  2]
 [12 16 26 12]
 [ 3  2  1  0]] 

