## Vector Arithmetic:

In [1]:
import numpy as np

# Define the variables for the vectors u and v
u = np.array([2, 5])
v = np.array([4, 7])

# Perform the calculations
answer_1 = u - v
answer_2 = u + v
answer_3 = 3 * u - 5 * v
answer_4 = 2 * u + 4 * v

# Create f-string print statements for each answer
print(f'Answer for problem 1 (u - v): {answer_1}')
print(f'Answer for problem 2 (u + v): {answer_2}')
print(f'Answer for problem 3 (3u - 5v): {answer_3}')
print(f'Answer for problem 4 (2u + 4v): {answer_4}')


Answer for problem 1 (u - v): [-2 -2]
Answer for problem 2 (u + v): [ 6 12]
Answer for problem 3 (3u - 5v): [-14 -20]
Answer for problem 4 (2u + 4v): [20 38]


 ## Matrix Arithmetic

In [2]:
import numpy as np
from IPython.display import display, Markdown

# Define the matrices A and B
A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
B = np.array([[1, 1, 4], [3, 2, 5], [4, 0, 9]])

# Perform the matrix arithmetic calculations
answer_5 = A + B
answer_6 = A - B
answer_7 = 2 * A - 3 * B
answer_8 = 5 * A + 2 * B

# Use display to show each result in a formatted manner
display(Markdown('**Answer for problem 5 (A + B):**'))
display(answer_5)
display(Markdown('**Answer for problem 6 (A - B):**'))
display(answer_6)
display(Markdown('**Answer for problem 7 (2A - 3B):**'))
display(answer_7)
display(Markdown('**Answer for problem 8 (5A + 2B):**'))
display(answer_8)


**Answer for problem 5 (A + B):**

array([[ 4,  7,  5],
       [ 5,  8, 14],
       [ 9,  1, 12]])

**Answer for problem 6 (A - B):**

array([[ 2,  5, -3],
       [-1,  4,  4],
       [ 1,  1, -6]])

**Answer for problem 7 (2A - 3B):**

array([[  3,   9, -10],
       [ -5,   6,   3],
       [ -2,   2, -21]])

**Answer for problem 8 (5A + 2B):**

array([[17, 32, 13],
       [16, 34, 55],
       [33,  5, 33]])

In [3]:
from IPython.display import display

# Use display to show each result in a formatted manner
display('Answer for problem 5 (A + B):', answer_5)
display('Answer for problem 6 (A - B):', answer_6)
display('Answer for problem 7 (2A - 3B):', answer_7)
display('Answer for problem 8 (5A + 2B):', answer_8)


'Answer for problem 5 (A + B):'

array([[ 4,  7,  5],
       [ 5,  8, 14],
       [ 9,  1, 12]])

'Answer for problem 6 (A - B):'

array([[ 2,  5, -3],
       [-1,  4,  4],
       [ 1,  1, -6]])

'Answer for problem 7 (2A - 3B):'

array([[  3,   9, -10],
       [ -5,   6,   3],
       [ -2,   2, -21]])

'Answer for problem 8 (5A + 2B):'

array([[17, 32, 13],
       [16, 34, 55],
       [33,  5, 33]])

# Matrix/Vector Multiplication

In [4]:

from IPython.display import display, Markdown

# Define the matrix A and vectors u, w
A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
u = np.array([3, 1, 2])
w = np.array([0, 1, 0])

# Define the matrix B and vector v
B = np.array([[1, 1, 4, 9], [3, 2, 5, 1], [2, 5, 1, 7]])
v = np.array([2, 5, 9, 7])

# Perform the matrix-vector multiplications
answer_9 = A.dot(u)
answer_10 = B.dot(v)
answer_11 = A.dot(w)

# Display the results using the display function
display(Markdown('**Answer for problem 9 (Au):**'))
display(answer_9)
display(Markdown('**Answer for problem 10 (Bv):**'))
display(answer_10)
display(Markdown('**Answer for problem 11 (Aw):**'))
display(answer_11)


**Answer for problem 9 (Au):**

array([17, 30, 22])

**Answer for problem 10 (Bv):**

array([106,  68,  87])

**Answer for problem 11 (Aw):**

array([6, 6, 1])

## Matrix Multiplication

In [5]:
import numpy as np
from IPython.display import display, Markdown

# Define the matrices A, B, C, and D
A = np.array([[3, 6, 1], [2, 6, 9], [5, 1, 3]])
B = np.array([[1, 1, 4], [3, 2, 5], [4, 0, 9]])
C = np.array([[1, 4], [6, 2], [0, 1]])
D = np.array([[1, 2, 4, 2], [3, 2, 1, 0]])

# Perform the matrix multiplication operations
answer_12 = A.dot(B)
answer_13 = B.dot(A)
answer_14 = C.dot(D)

# Display the results using the display function
display(Markdown('**Answer for problem 12 (AB):**'))
display(answer_12)
display(Markdown('**Answer for problem 13 (BA):**'))
display(answer_13)
display(Markdown('**Answer for problem 14 (CD):**'))
display(answer_14)


**Answer for problem 12 (AB):**

array([[ 25,  15,  51],
       [ 56,  14, 119],
       [ 20,   7,  52]])

**Answer for problem 13 (BA):**

array([[25, 16, 22],
       [38, 35, 36],
       [57, 33, 31]])

**Answer for problem 14 (CD):**

array([[13, 10,  8,  2],
       [12, 16, 26, 12],
       [ 3,  2,  1,  0]])